### ISSUE TITLE
django.db.utils.DataError: value too long for type character varying(45)

### ISSUE THREAD

**Issue by JMIdeaMaker** [pinax/pinax-referrals#57]
I get the error in the title when I visit any referral link (in production -- locally everything works fine). What could be wrong?

Example: https://www.datafix.io/referrals/fw7NBRL0x4j6q4mOO5QLUv6rw5pLzjv7oaZTxhjO/

**Comment by KatherineMichel** [comment]
@mikejohnsonjr I wonder if it has to do with the old `ReferralResponse` `ip_address` limit. It used to be 45, but was recently updated to 265. Looks like the migrations file still shows 45. https://github.com/pinax/pinax-referrals/blob/23489898f0785b788dc68a32cff3213bf6a4d732/pinax/referrals/migrations/0001_initial.py#L39
https://github.com/pinax/pinax-referrals/blob/master/pinax/referrals/models.py#L150

The fix was discussed in this issue: https://github.com/pinax/pinax-referrals/issues/46

**Comment by ckrybus** [comment]
@PetrDlouhy please close the issue, the bug was fixed  a while ago
